name: Docker Image CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  schedule:
    - cron: '0 0 28 * *'

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - if: github.ref == 'refs/heads/master'
        name: Conditional(Set tag as `latest`)
        run: echo "tag=volschin/fhem-collectord:latest" >> $GITHUB_ENV

      - if: startsWith(github.ref, 'refs/tags/')
        name: Conditional(Set tag as `{version}`)
        run: echo "tag=volschin/fhem-collectord:${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.tag }}
